services:
  - type: web
    name: ai-bias-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://bias_database_owner:npg_FRIWYb6cd9xO@ep-frosty-math-a1ppdasj-pooler.ap-southeast-1.aws.neon.tech/bias_database?sslmode=require
      - key: FRONTEND_URL
        value: https://ai-bias-detector-coral.vercel.app
