# Generated by Django 5.1.7 on 2025-03-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitive_feature', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('demographic_parity_difference', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bias.uploadeddataset')),
            ],
        ),
    ]
