# Generated by Django 5.1.7 on 2025-03-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias', '0002_biasanalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasCorrectionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField()),
                ('applied', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('data', 'Data Fix'), ('model', 'Model Fix'), ('feature', 'Feature Fix')], default='model', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bias.biasanalysisresult')),
            ],
        ),
    ]
